version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/bmart/server/
permission:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/before_server_deploy.sh
  AfterInstall:
    - location: scripts/after_server_deploy.sh
